### ISSUE TITLE
incompatible public key algorithms

### ISSUE THREAD

**Issue by dumheter** [SEP-G5/Mobile-Client#16]
Without talking to eachother, @LionelJouin , we both implemeted the public key cryptography part which we need for signing transactions. And we chose incompatible algorithms :S (closed in PR #15 )

Here we are using the RSA algorithm, which needs to be ~2000 bits to be "secure".

In backend we chose to use ed25519, which only needs 256 bits to be "secure".

I suggest we use ed25519 for more compact public keys, which ultimately will be stored (twice for every transaction, input & output) in the blockchain. Also, most cryptos use elliptic curve based public key algorithms for this very reason, more compact keys.

I am using the rust version of [libsodium](https://github.com/jedisct1/libsodium), a popular encryption library. And I found that there is [javascript bindings for it](https://github.com/paixaop/node-sodium) . It should make for an easy time for us to be compatible. Also, it seems to have a [key management system](https://github.com/paixaop/node-sodium/blob/master/docs/key-manager.md) which should make that part easier for you, (storing the key safely).

Here is some articles I based my decision on:  
http://ed25519.cr.yp.to/
https://security.stackexchange.com/questions/143442/what-are-ssh-keygen-best-practices
https://medium.com/risan/upgrade-your-ssh-key-to-ed25519-c6e8d60d3c54

**Comment by LionelJouin** [comment]
Yes, I have put RSA to wait for the decision about public key cryptography algorithm we would choose. In addition to the argument about the size of the key, RSA tooks too much time to generate the keys (~30 seconds on mobile). I will take a look at ed25519, the library you sent seems to be for node-js, I'm not sure if I can use it, I will try, otherwise I will check if there is any other available.

About the storage, it is not secure yet, I will take a look to that part next week. The current storage which has been implemented is using native storage of Android, Ios, and the browser.

**Comment by dumheter** [comment]
Oh wow, 30 seconds! The ed25519 algo is supposed to be super fast, should fix that.

I see that the javascript sodium library was only for nodejs. Try [this one instead](https://github.com/jedisct1/libsodium.js/)
